### ISSUE TITLE
Preloader no showing

### ISSUE THREAD

**Issue by Ninjadoodle** [ekelokorpi/panda-engine#181]
The preloading bar that usually shows when loading assets doesn't seem to show in the latest dev version, and all I get is a black screen while loading -> then the content shows.

**Comment by ekelokorpi** [comment]
Yes that is intentional. Loader class has been simplified and there is no any graphics by default.

You can easily create your own loader by simply injecting `Loader` class, create graphics at `init` function and change them at `onProgress` function, that is called when file is loaded. Loader class is just a extended `Scene` class with some loading functions. Also you can create multiple different loaders by extending the class and you can change the default startup loader by changing the class name at `game.System.loader`
